/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-338
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3';


// Services

export interface ShopServiceDef {
    list: (callParams: CallParams<null>) => { address: string; id: string; price: number; title: string; }[] | Promise<{ address: string; id: string; price: number; title: string; }[]>;
    list_by_keyword: (search: string, callParams: CallParams<'search'>) => { address: string; id: string; price: number; title: string; }[] | Promise<{ address: string; id: string; price: number; title: string; }[]>;
}
export function registerShopService(service: ShopServiceDef): void;
export function registerShopService(serviceId: string, service: ShopServiceDef): void;
export function registerShopService(peer: FluencePeer, service: ShopServiceDef): void;
export function registerShopService(peer: FluencePeer, serviceId: string, service: ShopServiceDef): void;
       

export function registerShopService(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "shopservice",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "list" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "array",
                            "type" : {
                                "tag" : "struct",
                                "name" : "Product",
                                "fields" : {
                                    "address" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "id" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "price" : {
                                        "tag" : "scalar",
                                        "name" : "u32"
                                    },
                                    "title" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            "list_by_keyword" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "search" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "array",
                            "type" : {
                                "tag" : "struct",
                                "name" : "Product",
                                "fields" : {
                                    "address" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "id" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "price" : {
                                        "tag" : "scalar",
                                        "name" : "u32"
                                    },
                                    "title" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions

